### PR TITLE
Add more examples

### PR DESCRIPTION
**Pull request by mchristou**
PR  for #57

### CODE REVIEW

**Comment by radumarias** [comment]
@mchristou is this still work in progress?

**Comment by mchristou** [comment]
I believe there are already very good examples, and with this PR, the coverage of the examples seems sufficient. Should we consider closing it?

**Comment by radumarias** [comment]
I agree. This is ready to be merged?

**Review by radumarias — APPROVED** [review]

**Comment by radumarias** [comment]
can you close the issue too?

**Pull request merged**
